Support `Color?` and `Vector3?` in elements code generation
hypar-io/Elements pull request #1011
Opened 2023-08-23 14:02 UTC by andrewheumann

BACKGROUND:
- In the Hypar CLI, we have supported nullable `Color` and `Vector3` values for a while, as of https://github.com/hypar-io/Hypar/pull/403 and https://github.com/hypar-io/Hypar/pull/492. However, we never brought these improvements over to Elements, meaning that it was supported in `input_schema` / `overrides` but not in element schemas. 

DESCRIPTION:
- Moves the Type Generator from `hypar` to `Elements`

TESTING:
- I tested this in tandem w/ `hypar init`, and I also wrote a test to ensure that the correct types are generated. 
  
FUTURE WORK:
- Once this is in, we should update `Hypar` to use it instead of having duplicated code. 

REQUIRED:
- [X] All changes are up to date in `CHANGELOG.md`.

2023-08-24 00:00 UTC, anthonie-kramer requested changes
What is the strategy for handling a `struct` definition vs an `object` definition? Are we expecting users to convert their `Nullable` types into the `Elements` `struct` types to use in a function?

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1011#-:-NcZo2G07mYyfPTRnjHh:b-kh9pn)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @andrewheumann)

___
*[`Elements.CodeGeneration/test/TestData/NullableAndNonNullableTypesSchema.json` line 62 at r1](https://reviewable.io/reviews/hypar-io/Elements/1011#-NcZnAAc9QZroACzwSfa:-NcZnAAd6omufN1-fT8i:b-pdcw8h) ([raw file](https://github.com/hypar-io/Elements/blob/114872a080b2d50a1cda5524cb3133eecba49616/Elements.CodeGeneration/test/TestData/NullableAndNonNullableTypesSchema.json#L62)):*
> ```JSON
>             "title": "Color"
>         },
>         "NullableColor": {
> ```

Isn't this the`NonNullableColor`, and the one above is the `NullableColor` ?


<!-- Sent from Reviewable.io -->

2023-08-24 18:38 UTC, andrewheumann reviewed
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1011)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @anthonie-kramer)

___
*[`Elements.CodeGeneration/test/TestData/NullableAndNonNullableTypesSchema.json` line 62 at r1](https://reviewable.io/reviews/hypar-io/Elements/1011#-NcZnAAc9QZroACzwSfa:-NccpXSB-gaoPvvjLLss:by7keby) ([raw file](https://github.com/hypar-io/Elements/blob/114872a080b2d50a1cda5524cb3133eecba49616/Elements.CodeGeneration/test/TestData/NullableAndNonNullableTypesSchema.json#L62)):*
<details><summary><i>Previously, anthonie-kramer (Anthonie Kramer) wrote…</i></summary><blockquote>

Isn't this the`NonNullableColor`, and the one above is the `NullableColor` ?
</blockquote></details>

No, `Color.json` is nullable (type ["object", "null"] ), and NonNullableColor is type `"object"`.


<!-- Sent from Reviewable.io -->

2023-08-24 18:40 UTC, andrewheumann reviewed
Objects are always nullable — we don't need to `?` them. This only matters for types which are already `struct`s in Elements, like Color and Vector3

> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1011#-:-NccpmPOBNNYN3hkKHWX:bfytrgn)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @anthonie-kramer)



<!-- Sent from Reviewable.io -->

2023-08-25 17:21 UTC, anthonie-kramer approved these changes
Right, I am just trying to understand the purpose of nullability, since the `Elements` `Vector3` is a `struct`... I am guessing that the schema-based `Vector3.json` is just used for object creation on the front end and then converted at some point to the `Elements` version for use in functions.

Anyway, I won't hold this up, just curious!

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1011#-:-NcheaIaBMJbHqlaBw-C:b-unqxj4)* status: :shipit: complete! 1 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2023-08-25 17:37 UTC, andrewheumann reviewed
both `Vector3` and `Color` are built-in types in elements which are implemented as `struct`s. We do a thing when doing codegen — for both Elements and inputs — where we check if a type already exists in the `dependencies` project, so that we can avoid generating a conflicting type. It happens that the `Color` schema is already configured to be nullable by default, whereas the `Vector3` schema is not.

> *[Reviewable](https://reviewable.io/reviews/hypar-io/Elements/1011#-:-NchkPyn9oBIu6AyHonf:b-y520ee)* status: :shipit: complete! 1 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2023-08-25 17:40 UTC, merged