use approx for pointAt and epsilon for divide by
hypar-io/Elements pull request #442
Opened 2020-11-05 22:34 UTC by wynged

BACKGROUND:
- Failed to get all segments for a line when asking for divide by

DESCRIPTION:
- Add a tolerance to the check of whether to stop segmenting, approxEquals for endpoint checks in PointAt, and a test

TESTING:
- run the test.

2020-11-06 13:08 UTC, andrewheumann requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/442)* status: all files reviewed, 1 unresolved discussion (waiting on @wynged)

___
*[Elements/src/Geometry/Line.cs, line 386 at r1](https://reviewable.io/reviews/hypar-io/elements/442#-MLSel-1D2uLWsJ014dr:-MLSel-1D2uLWsJ014ds:b8mfkrx) ([raw file](https://github.com/hypar-io/elements/blob/1f2ac7c7737f478ff05e147c26f1f3b5f7fa5bb5/Elements/src/Geometry/Line.cs#L386)):*
> ```Smalltalk
>             var lines = new List<Line>();
>             var div = 1.0 / (n + 1);
>             for (var t = 0.0; t <= 1.0 - div + Vector3.EPSILON; t += div)
> ```

this is a nit but it feels strange to have `<=` when we're comparing against something that has a tolerance built in. 


<!-- Sent from Reviewable.io -->

2020-11-06 16:22 UTC, wynged reviewed
responded to nit and also renamed method

> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/442#-:-MLTMShK5XbdEvWh5Hg7:b7wxj80)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @andrewheumann)

___
*[Elements/src/Geometry/Line.cs, line 386 at r1](https://reviewable.io/reviews/hypar-io/elements/442#-MLSel-1D2uLWsJ014dr:-MLTMR_B2j3v9IjW1dcC:bb7f2mf) ([raw file](https://github.com/hypar-io/elements/blob/1f2ac7c7737f478ff05e147c26f1f3b5f7fa5bb5/Elements/src/Geometry/Line.cs#L386)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

this is a nit but it feels strange to have `<=` when we're comparing against something that has a tolerance built in. 
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2020-11-09 12:33 UTC, andrewheumann requested changes
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/442)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @andrewheumann and @wynged)

___
*[Elements/src/Geometry/Line.cs, line 380 at r2](https://reviewable.io/reviews/hypar-io/elements/442#-MLgzf7dCB6yQsDiUo0R:-MLgzf7dCB6yQsDiUo0S:bfdrk0q) ([raw file](https://github.com/hypar-io/elements/blob/3007cc05e1e5107aab9a6c65a66449ee9a642f0f/Elements/src/Geometry/Line.cs#L380)):*
> ```Smalltalk
>         public List<Line> DivideIntoEqualSegments(int n)
>         {
>             if (n < 0)
> ```

<= 0 or < 1
___
*[Elements/src/Geometry/Line.cs, line 385 at r2](https://reviewable.io/reviews/hypar-io/elements/442#-MLgzlJbDHw1FTl1st34:-MLgzlJcB4J_im38xXcG:b-8s3rc0) ([raw file](https://github.com/hypar-io/elements/blob/3007cc05e1e5107aab9a6c65a66449ee9a642f0f/Elements/src/Geometry/Line.cs#L385)):*
> ```Smalltalk
>             }
>             var lines = new List<Line>();
>             var div = 1.0 / (n );
> ```

remove parens


<!-- Sent from Reviewable.io -->

2020-11-09 16:06 UTC, wynged reviewed
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/442)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @andrewheumann)

___
*[Elements/src/Geometry/Line.cs, line 380 at r2](https://reviewable.io/reviews/hypar-io/elements/442#-MLgzf7dCB6yQsDiUo0R:-MLhkYB31QdfGk22rf_F:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/3007cc05e1e5107aab9a6c65a66449ee9a642f0f/Elements/src/Geometry/Line.cs#L380)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

<= 0 or < 1
</blockquote></details>

Done.
___
*[Elements/src/Geometry/Line.cs, line 385 at r2](https://reviewable.io/reviews/hypar-io/elements/442#-MLgzlJbDHw1FTl1st34:-MLhkYSXBBVPHDv77WYl:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/3007cc05e1e5107aab9a6c65a66449ee9a642f0f/Elements/src/Geometry/Line.cs#L385)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

remove parens
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-09 19:51 UTC, andrewheumann approved these changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/442)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-10 17:19 UTC, merged