Implement parametric profile.
hypar-io/Elements pull request #697
Opened 2021-11-03 14:51 UTC by ikeough

BACKGROUND:
See #696 

DESCRIPTION:
- This PR adds a new type, `ParametricProfile` which derives from `Profile` and enables the user to specify the profile's vertex locations using expressions for X, Y, and Z.

TESTING:
- See `ParametricProfileTests`
  
FUTURE WORK:
- Currently you have to use the word `data` in your expressions. As an example, you reference your `width` parameter by writing `data.width`. This is due to a limitation in C#'s dynamic compilation. In the future I'd like to remove this requirement so that a user can simply write `width`.

REQUIRED:
- [x] All changes are up to date in `CHANGELOG.md`.

![image](https://user-images.githubusercontent.com/1139788/140083654-16a15c3d-d2ff-413d-b038-f77eba3f7d5a.png)

2021-11-03 17:09 UTC, radumg commented on Elements/src/Geometry/Profiles/ParametricProfile.cs
> +            Perimeter = CreatePolygonFromExpressions(data.PerimeterVectorExpressions, data.PropertyValues, _refs).Result;
using `.Result` in ctors can/will likely result in deadlocks
https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#constructors

2021-11-05 11:04 UTC, andrewheumann requested changes
> Reviewed 2 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/697)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough and @radumg)

___
*[Elements/src/Geometry/Profile.cs, line 26 at r2](https://reviewable.io/reviews/hypar-io/elements/697#-Mnjknwv2mcCiDaftnXp:-Mnjknww36zxsQYFHALE:b-haxd4x) ([raw file](https://github.com/hypar-io/elements/blob/21a28b9b2b794c44c81dd063bd8a2cf1cadc39de/Elements/src/Geometry/Profile.cs#L26)):*
> ```Smalltalk
>         /// and is not intended to be used directly.
>         /// </summary>
>         public Profile() { }
> ```

should this be `internal`, rather than `public`?
___
*[Elements/src/Geometry/Profile.cs, line 266 at r2](https://reviewable.io/reviews/hypar-io/elements/697#-MnjixpA-gAj1yjeB0LF:-MnjixpA-gAj1yjeB0LG:bm73xh0) ([raw file](https://github.com/hypar-io/elements/blob/21a28b9b2b794c44c81dd063bd8a2cf1cadc39de/Elements/src/Geometry/Profile.cs#L266)):*
> ```Smalltalk
>             // profile which defines its own perimeter and void logic
>             // during construction.
>             if (Perimeter == null || Voids == null)
> ```

are we 100% sure that profiles can't ever have null Voids in non-parametric profile cases? I think this is still possible See the `Profile(Polygon perimeter, Polygon @void)` constructor for one way to construct profiles that doesn't involve checking for a null `Voids` array. (We should probably just fix that instead of this, but maybe a `if this is ParametricProfile` or something would be prudent too?)
___
*[Elements/src/Geometry/Profiles/ParametricProfile.cs, line 23 at r2](https://reviewable.io/reviews/hypar-io/elements/697#-MnjkwD32NuwZXDl1rO8:-MnjkwD32NuwZXDl1rO9:bm40a6p) ([raw file](https://github.com/hypar-io/elements/blob/21a28b9b2b794c44c81dd063bd8a2cf1cadc39de/Elements/src/Geometry/Profiles/ParametricProfile.cs#L23)):*
> ```Smalltalk
>         /// The data which defines the profile.
>         /// </summary>
>         public ParametericProfileData Data { get; set; }
> ```

Parameteric  => Parametric


<!-- Sent from Reviewable.io -->

2021-11-06 16:47 UTC, ikeough reviewed
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/697)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @andrewheumann and @radumg)

___
*[Elements/src/Geometry/Profile.cs, line 26 at r2](https://reviewable.io/reviews/hypar-io/elements/697#-Mnjknwv2mcCiDaftnXp:-Mnq7cIK8Wj0ePfuSpDR:bb6un1j) ([raw file](https://github.com/hypar-io/elements/blob/21a28b9b2b794c44c81dd063bd8a2cf1cadc39de/Elements/src/Geometry/Profile.cs#L26)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

should this be `internal`, rather than `public`?
</blockquote></details>

Done
___
*[Elements/src/Geometry/Profile.cs, line 266 at r2](https://reviewable.io/reviews/hypar-io/elements/697#-MnjixpA-gAj1yjeB0LF:-Mnq7jXzA_JmCGip0kpn:b3nnnqt) ([raw file](https://github.com/hypar-io/elements/blob/21a28b9b2b794c44c81dd063bd8a2cf1cadc39de/Elements/src/Geometry/Profile.cs#L266)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

are we 100% sure that profiles can't ever have null Voids in non-parametric profile cases? I think this is still possible See the `Profile(Polygon perimeter, Polygon @void)` constructor for one way to construct profiles that doesn't involve checking for a null `Voids` array. (We should probably just fix that instead of this, but maybe a `if this is ParametricProfile` or something would be prudent too?)
</blockquote></details>

In any case where voids can be null, this would be necessary. Are you asking if I should just remove the comment? 
___
*[Elements/src/Geometry/Profiles/ParametricProfile.cs, line 23 at r2](https://reviewable.io/reviews/hypar-io/elements/697#-MnjkwD32NuwZXDl1rO8:-Mnq8KGz7cTRVP5HCwKZ:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/21a28b9b2b794c44c81dd063bd8a2cf1cadc39de/Elements/src/Geometry/Profiles/ParametricProfile.cs#L23)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

Parameteric  => Parametric
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-06 21:14 UTC, andrewheumann requested changes
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/697)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough and @radumg)

___
*[Elements/src/Geometry/Profile.cs, line 266 at r2](https://reviewable.io/reviews/hypar-io/elements/697#-MnjixpA-gAj1yjeB0LF:-Mnr5VIi0NxnSypUeZFS:blswq4s) ([raw file](https://github.com/hypar-io/elements/blob/21a28b9b2b794c44c81dd063bd8a2cf1cadc39de/Elements/src/Geometry/Profile.cs#L266)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

In any case where voids can be null, this would be necessary. Are you asking if I should just remove the comment? 
</blockquote></details>

oh, that makes sense — was thrown off by the comment. disregard.


<!-- Sent from Reviewable.io -->

2021-11-06 21:16 UTC, andrewheumann reviewed
> Reviewed 1 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/697)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough and @radumg)



<!-- Sent from Reviewable.io -->

2021-11-09 06:05 UTC, merged