fix for string enum codegen
hypar-io/Elements pull request #807
Opened 2022-05-19 19:46 UTC by andrewheumann

BACKGROUND:
- CodeGen of enums would sometimes result in invalid C# code. Even though we have `using Newtonsoft.Json` in the class template, because we didn't have `using Newtonsoft.Json.Converters`, this would not build.

DESCRIPTION:
- fully qualifies `Newtonsoft.Json.Converters.StringEnumConverter`

TESTING:
- I tested this with a local build of the Hypar CLI which references this version of elements, and verified that string enums no longer generated invalid code.

2022-05-20 13:51 UTC, wynged approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/807)* status: :shipit: complete! 1 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2022-05-20 13:52 UTC, wynged requested changes
code looks fine but.. failing test?

> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/807#-:-N2WjILBAUHIHQkJ99UU:b-dyiuca)* status: 1 change requests, 0 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2022-05-22 14:19 UTC, andrewheumann reviewed
seems like was just a fluke? re-ran and is passing.

> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/807#-:-N2g7_bx6qn67HakhG-8:b-w4v0hy)* status: 1 change requests, 0 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2022-05-23 19:41 UTC, wynged approved these changes
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/807)* status: :shipit: complete! 1 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2022-05-23 19:55 UTC, merged