AdaptiveGraphRouting: add WeightModifier and EdgeInfo.Flags
hypar-io/Elements pull request #920
Opened 2022-11-25 10:29 UTC by DmytroMuravskyi

BACKGROUND:
- Support of 3D routing required more flexible way to set weight modifiers to regions of the grid instead of just main layer and penalty.

DESCRIPTION:
- Added WeightModifier object that hold function that allows to apply factor multiplier to edge travel cost.
If edge passes check of several WeightModifier objects - lowest factor is chosen.
- Added Flags field to EdgeInfo to hold additional information, like is edge used by and hint line, without inflating object size too much.

TESTING:
- Added AdaptiveGraphRoutingWeightModifier test.
  
FUTURE WORK:
- 3D routing is complex topic so code can still undergo changes.

REQUIRED:
- [x] All changes are up to date in `CHANGELOG.md`.

COMMENTS:
- Not sure if we need marking code "Obsolete". Let me know if I just need to remove it.

2022-11-28 04:11 UTC, wynged requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/920)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @DmytroMuravskyi)

___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs` line 109 at r1](https://reviewable.io/reviews/hypar-io/elements/920#-NHwJNvuBqmXXZAczNgb:-NHwJNvuBqmXXZAczNgc:b-35uxzx) ([raw file](https://github.com/hypar-io/elements/blob/98e7714306e71252de398e3d1124b6ca9f766f8c/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs#L109)):*
> ```Smalltalk
>                 if (IsAffectedBy(v0.Point, v1.Point, userHints))
>                 {
>                     if (modifierFactor < 1 + _grid.Tolerance)
> ```

coloring based on > or < 1 doesn't feel comprehensive enough given the new modifier factor scheme.  could we have modifier factors also have a color?  Create a property on the WeightModifier object for a color that can be controlled by a developer or let a default random color be assigned to the modifier. Whichever weither modifer "wins" should be the color of the edge.
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs` line 466 at r1](https://reviewable.io/reviews/hypar-io/elements/920#-NHwJ9uT7OwNuYJdMqZG:-NHwJ9uU0hsNrZEJp4yt:b-txh2jv) ([raw file](https://github.com/hypar-io/elements/blob/98e7714306e71252de398e3d1124b6ca9f766f8c/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs#L466)):*
> ```Smalltalk
>                                 {
>                                     hintFactor = Math.Min(l.Factor, hintFactor);
>                                     flags &= l.Is2D ? EdgeFlags.Hint2D : EdgeFlags.Hint3D;
> ```

can we write a comment about what this is for?  
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRoutingWeightModifier.cs` line 55 at r1](https://reviewable.io/reviews/hypar-io/elements/920#-NHwKjn14kGkfFdTvjg4:-NHwKjn14kGkfFdTvjg5:b-db113l) ([raw file](https://github.com/hypar-io/elements/blob/98e7714306e71252de398e3d1124b6ca9f766f8c/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRoutingWeightModifier.cs#L55)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// Create WeightModifier that sets factor to all edges lying on given plane.
> ```

phrasing "...that sets the factor on all edges lying on a given plane"
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRoutingWeightModifier.cs` line 61 at r1](https://reviewable.io/reviews/hypar-io/elements/920#-NHwKfylCoSqumoVQQa7:-NHwKfylCoSqumoVQQa8:b-dq552k) ([raw file](https://github.com/hypar-io/elements/blob/98e7714306e71252de398e3d1124b6ca9f766f8c/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRoutingWeightModifier.cs#L61)):*
> ```Smalltalk
>         /// <param name="factor">Factor of new WeightModifier.</param>
>         /// <returns>Created WeightModifier.</returns>
>         public WeightModifier AddPlaneModifier(string name, Plane plane, double factor)
> ```

rename to AddPlanarWeightModifier for clarity i think.
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRoutingWeightModifier.cs` line 74 at r1](https://reviewable.io/reviews/hypar-io/elements/920#-NHwK7ih06mYX_VixYyh:-NHwK7ih06mYX_VixYyi:band6f6) ([raw file](https://github.com/hypar-io/elements/blob/98e7714306e71252de398e3d1124b6ca9f766f8c/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRoutingWeightModifier.cs#L74)):*
> ```Smalltalk
>             return modifier;
>         }
> ```

Just a question, we don't need to act now, but should Hint lines just be another kind of weight modifier, or at least use the WeightModifier infrastructure?  They have a role to play in generating the graph but their weights could be managed as "AddLinerWeightModifiers" separately from the grid creation.  Let's at least add a TODO nearby where HintLine weights are applied f you think we should move that direction.
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRoutingWeightModifier.cs` line 77 at r1](https://reviewable.io/reviews/hypar-io/elements/920#-NHwLQ4v-DUPzNhemg5r:-NHwLQ4v-DUPzNhemg5s:b-kq4qkt) ([raw file](https://github.com/hypar-io/elements/blob/98e7714306e71252de398e3d1124b6ca9f766f8c/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRoutingWeightModifier.cs#L77)):*
> ```Smalltalk
>         private double ModifierFactor(Vertex a, Vertex b)
>         {
>             double modifierFactor = -1;
> ```

-1 is a confusing value here, since we're looking for the "min" shouldn't we have this set to MaxValue?  Or maybe better, have it be a `double?` so that we can return null if there is no modified value, and then just don't modify the value if a null is returned.  
___
*[`Elements/src/Spatial/AdaptiveGrid/EdgeInfo.cs` line 31 at r1](https://reviewable.io/reviews/hypar-io/elements/920#-NHwM4h5A9vmF_wi1ehS:-NHwM4h6CwcHdlP4GcCH:bmgyz5k) ([raw file](https://github.com/hypar-io/elements/blob/98e7714306e71252de398e3d1124b6ca9f766f8c/Elements/src/Spatial/AdaptiveGrid/EdgeInfo.cs#L31)):*
> ```Smalltalk
>             if (Math.Abs(v0.Point.Z - v1.Point.Z) > grid.Tolerance)
>             {
>                 Flags &= EdgeFlags.HasVerticalChange;
> ```

To a less experienced developer this is confusing, what does &= with an enum produce... ?
we need to comment here that this is a behavior of a "Flags" enum being treated as a bit set, ans so this is adding the flag to the set of stored flags.
___
*[`Elements/src/Spatial/AdaptiveGrid/EdgeInfo.cs` line 63 at r1](https://reviewable.io/reviews/hypar-io/elements/920#-NHwNlC98Fv_2BlnMq6e:-NHwNlC98Fv_2BlnMq6f:bayii8c) ([raw file](https://github.com/hypar-io/elements/blob/98e7714306e71252de398e3d1124b6ca9f766f8c/Elements/src/Spatial/AdaptiveGrid/EdgeInfo.cs#L63)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// Check if edge info has certain flag or combination of flags set.
> ```

phrasing  "...has a certain flag"
___
*[`Elements/src/Spatial/AdaptiveGrid/EdgeInfo.cs` line 65 at r1](https://reviewable.io/reviews/hypar-io/elements/920#-NHwNdSKAFvuVc1rpXIe:-NHwNdSL4b-8jgtyQELv:bva2f0t) ([raw file](https://github.com/hypar-io/elements/blob/98e7714306e71252de398e3d1124b6ca9f766f8c/Elements/src/Spatial/AdaptiveGrid/EdgeInfo.cs#L65)):*
> ```Smalltalk
>         /// Check if edge info has certain flag or combination of flags set.
>         /// </summary>
>         /// <param name="flag">Flag or combination of flags to check.</param>
> ```

how does one submit a combination of flags for this check.  can we write teh code that would do that in this comment?
___
*[`Elements/src/Spatial/AdaptiveGrid/EdgeInfo.cs` line 74 at r1](https://reviewable.io/reviews/hypar-io/elements/920#-NHwN-tY5DPp_NqAd8pp:-NHwN-tY5DPp_NqAd8pq:b-b6m26e) ([raw file](https://github.com/hypar-io/elements/blob/98e7714306e71252de398e3d1124b6ca9f766f8c/Elements/src/Spatial/AdaptiveGrid/EdgeInfo.cs#L74)):*
> ```Smalltalk
> 
>     /// <summary>
>     /// Bit set of flags storing describing information about edge.
> ```

ok, Bit sets and flags attribute are cool but also new to me and unusual for our users I think.  We'll need a short description of what is going on here, and 
___
*[`Elements/src/Spatial/AdaptiveGrid/EdgeInfo.cs` line 77 at r1](https://reviewable.io/reviews/hypar-io/elements/920#-NHwML1nCu-FU6tOFNk9:-NHwML1nCu-FU6tOFNkA:b-jzzjuo) ([raw file](https://github.com/hypar-io/elements/blob/98e7714306e71252de398e3d1124b6ca9f766f8c/Elements/src/Spatial/AdaptiveGrid/EdgeInfo.cs#L77)):*
> ```Smalltalk
>     /// </summary>
>     [Flags]
>     public enum EdgeFlags
> ```

separate file for enum.
___
*[`Elements/src/Spatial/AdaptiveGrid/WeightModifier.cs` line 8 at r1](https://reviewable.io/reviews/hypar-io/elements/920#-NHwO4cN1RmnkiMw3IlN:-NHwO4cN1RmnkiMw3IlO:bk0jeg8) ([raw file](https://github.com/hypar-io/elements/blob/98e7714306e71252de398e3d1124b6ca9f766f8c/Elements/src/Spatial/AdaptiveGrid/WeightModifier.cs#L8)):*
> ```Smalltalk
> {
>     /// <summary>
>     /// Object that hold function that allows to apply factor multiplier to edge travel cost.
> ```

phrasing.   "Object that lets [...]

2022-11-29 04:06 UTC, wynged approved these changes
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/920)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @DmytroMuravskyi)

___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs` line 455 at r2](https://reviewable.io/reviews/hypar-io/elements/920#-NI0WYlI-H2aa3sBAsPU:-NI0WYlJ8gIM6atJuD6W:b-rzqm7c) ([raw file](https://github.com/hypar-io/elements/blob/b8c972fba0e349bbea8c7dd8e657fbcf391944c2/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs#L455)):*
> ```Smalltalk
> 
>                     //TODO: consider unifying hint line, offset line and modifiers as single concept.
>                     //There still be functions for adding hint/offset lines but everything will be processes inside
> ```

phrasing.  "There will still be functions for adding hint/offset lines but everything will be processed inside..."
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs` line 456 at r2](https://reviewable.io/reviews/hypar-io/elements/920#-NI0XDn13dnNNC6O44_W:-NI0XDn205Glq3uzojza:b-a9g4h8) ([raw file](https://github.com/hypar-io/elements/blob/b8c972fba0e349bbea8c7dd8e657fbcf391944c2/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs#L456)):*
> ```Smalltalk
>                     //TODO: consider unifying hint line, offset line and modifiers as single concept.
>                     //There still be functions for adding hint/offset lines but everything will be processes inside
>                     //as WeightModifier. Would need to solve function that takes list of groups and define how
> ```

phrasing.  "We would need to decide on the function that takes a list of these weight modifier groups and defines how multiple factors are combined together..."
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRoutingWeightModifier.cs` line 76 at r2](https://reviewable.io/reviews/hypar-io/elements/920#-NI0WR1EEI0m6bbjCJkS:-NI0WR1EEI0m6bbjCJkT:b-vnwgax) ([raw file](https://github.com/hypar-io/elements/blob/b8c972fba0e349bbea8c7dd8e657fbcf391944c2/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRoutingWeightModifier.cs#L76)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// Check if edge passes any modifier check and return the lowest value among them.
> ```

"and returns"  add 's'
___
*[`Elements/src/Spatial/AdaptiveGrid/EdgeFlags.cs` line 8 at r2](https://reviewable.io/reviews/hypar-io/elements/920#-NI0W8iQ3A_KZC8gm4Az:-NI0W8iQ3A_KZC8gm4B-:b3jmpyn) ([raw file](https://github.com/hypar-io/elements/blob/b8c972fba0e349bbea8c7dd8e657fbcf391944c2/Elements/src/Spatial/AdaptiveGrid/EdgeFlags.cs#L8)):*
> ```Smalltalk
> {
>     /// <summary>
>     /// Bit set of flags storing describing information about edge.
> ```

remove "describing"
___
*[`Elements/src/Spatial/AdaptiveGrid/EdgeFlags.cs` line 12 at r2](https://reviewable.io/reviews/hypar-io/elements/920#-NI0WL7134ZKUrmU7K69:-NI0WL7134ZKUrmU7K6A:bytx14s) ([raw file](https://github.com/hypar-io/elements/blob/b8c972fba0e349bbea8c7dd8e657fbcf391944c2/Elements/src/Spatial/AdaptiveGrid/EdgeFlags.cs#L12)):*
> ```Smalltalk
>     /// Use | or |= to combine flags: flag = Hint2D | HasVerticalChange = 1 + 4 = 001 + 100 = 101 = 5.
>     /// Use & or &= to check of one or more flags: flags & Hint3D == 101 & 010 == 0 == None, but 
>     /// but flags & Hint2D == 101 & 001 == 001 == Hint2D.
> ```

remove extra "but"
___
*[`Elements/src/Spatial/AdaptiveGrid/EdgeInfo.cs` line 66 at r2](https://reviewable.io/reviews/hypar-io/elements/920#-NI0XkKd98YwJf8XyC5X:-NI0XkKd98YwJf8XyC5Y:b-o4xrm6) ([raw file](https://github.com/hypar-io/elements/blob/b8c972fba0e349bbea8c7dd8e657fbcf391944c2/Elements/src/Spatial/AdaptiveGrid/EdgeInfo.cs#L66)):*
> ```Smalltalk
>         /// </summary>
>         /// <param name="flag">Flag or combination of flags to check.
>         /// For example: HasFlag(Hint2D) or HasFlag(Hint2D | Hint3D).</param>
> ```

now it is "HasAnyFlag"
___
*[`Elements/src/Spatial/AdaptiveGrid/WeightModifier.cs` line 9 at r2](https://reviewable.io/reviews/hypar-io/elements/920#-NI0YiZRCRonMuOyNzjY:-NI0YiZRCRonMuOyNzjZ:b-47toxd) ([raw file](https://github.com/hypar-io/elements/blob/b8c972fba0e349bbea8c7dd8e657fbcf391944c2/Elements/src/Spatial/AdaptiveGrid/WeightModifier.cs#L9)):*
> ```Smalltalk
>     /// <summary>
>     /// Object that lets you apply an edge weight factor to edges that meet a Condition filter function.
>     /// If an edge meets the nameof(Condition) of several WeightModifier objects the lowest factor is chosen.
> ```

I had this wrong I think, does nameof work here?  maybe we should be using <see cref="..."/> https://stackoverflow.com/questions/54995797/can-you-use-nameof-or-another-technique-to-embed-a-procedure-name-in-a-code-co
___
*[`Elements/src/Spatial/AdaptiveGrid/WeightModifier.cs` line 32 at r2](https://reviewable.io/reviews/hypar-io/elements/920#-NI0YvTj6EU_DV01Vfya:-NI0YvTj6EU_DV01Vfyb:b-4szba9) ([raw file](https://github.com/hypar-io/elements/blob/b8c972fba0e349bbea8c7dd8e657fbcf391944c2/Elements/src/Spatial/AdaptiveGrid/WeightModifier.cs#L32)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// Filter function that the determines if this WeightModifier applies to an edge.
> ```

remove "the"  should be "that determines"


<!-- Sent from Reviewable.io -->

2022-11-29 12:25 UTC, DmytroMuravskyi reviewed
Thanks for all the review process.

> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/920#-:-NI2LApT-mCMegFS9Pu7:b-xvdjf4)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @wynged)

___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs` line 109 at r1](https://reviewable.io/reviews/hypar-io/elements/920#-NHwJNvuBqmXXZAczNgb:-NHyaysS3-btoIggeUxL:b-vhr558) ([raw file](https://github.com/hypar-io/elements/blob/98e7714306e71252de398e3d1124b6ca9f766f8c/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs#L109)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

coloring based on > or < 1 doesn't feel comprehensive enough given the new modifier factor scheme.  could we have modifier factors also have a color?  Create a property on the WeightModifier object for a color that can be controlled by a developer or let a default random color be assigned to the modifier. Whichever weither modifer "wins" should be the color of the edge.
</blockquote></details>

Yes that's right, however I don't think we should introduce color into data model:
-  It's hard to avoid color overlapping when to things are accidentally the same color.
- Since Edge can be affected by hint and modifier right now I wanted to distinguish hint edge and hint edge affected by modifier.
I was thinking about automatically painting edges in gradient from green to red, where yellow is factor of 1, less than that is green shifted and more than one is red shifted. What's about doing this as separate PR, maybe when we know what we want to do with edges affected by several modifiers?
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs` line 466 at r1](https://reviewable.io/reviews/hypar-io/elements/920#-NHwJ9uT7OwNuYJdMqZG:-NHxdCvi8I82okVgJprD:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/98e7714306e71252de398e3d1124b6ca9f766f8c/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs#L466)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

can we write a comment about what this is for?  
</blockquote></details>

Done.
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs` line 455 at r2](https://reviewable.io/reviews/hypar-io/elements/920#-NI0WYlI-H2aa3sBAsPU:-NI2Hp_445Bei_UFtgen:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/b8c972fba0e349bbea8c7dd8e657fbcf391944c2/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs#L455)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

phrasing.  "There will still be functions for adding hint/offset lines but everything will be processed inside..."
</blockquote></details>

Done.
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs` line 456 at r2](https://reviewable.io/reviews/hypar-io/elements/920#-NI0XDn13dnNNC6O44_W:-NI2I11qAK506Og3xiaS:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/b8c972fba0e349bbea8c7dd8e657fbcf391944c2/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs#L456)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

phrasing.  "We would need to decide on the function that takes a list of these weight modifier groups and defines how multiple factors are combined together..."
</blockquote></details>

Done.
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRoutingWeightModifier.cs` line 55 at r1](https://reviewable.io/reviews/hypar-io/elements/920#-NHwKjn14kGkfFdTvjg4:-NHxdCXDAelN5U1ReS1a:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/98e7714306e71252de398e3d1124b6ca9f766f8c/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRoutingWeightModifier.cs#L55)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

phrasing "...that sets the factor on all edges lying on a given plane"
</blockquote></details>

Done.
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRoutingWeightModifier.cs` line 61 at r1](https://reviewable.io/reviews/hypar-io/elements/920#-NHwKfylCoSqumoVQQa7:-NHxdHf-1f3xkmr_PAkd:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/98e7714306e71252de398e3d1124b6ca9f766f8c/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRoutingWeightModifier.cs#L61)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

rename to AddPlanarWeightModifier for clarity i think.
</blockquote></details>

Done.
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRoutingWeightModifier.cs` line 74 at r1](https://reviewable.io/reviews/hypar-io/elements/920#-NHwK7ih06mYX_VixYyh:-NHxgZH32C8p7_z6vjXt:b-2isfzp) ([raw file](https://github.com/hypar-io/elements/blob/98e7714306e71252de398e3d1124b6ca9f766f8c/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRoutingWeightModifier.cs#L74)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

Just a question, we don't need to act now, but should Hint lines just be another kind of weight modifier, or at least use the WeightModifier infrastructure?  They have a role to play in generating the graph but their weights could be managed as "AddLinerWeightModifiers" separately from the grid creation.  Let's at least add a TODO nearby where HintLine weights are applied f you think we should move that direction.
</blockquote></details>

Yes, we can do everything as WeightModifier, added a TODO for this.
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRoutingWeightModifier.cs` line 77 at r1](https://reviewable.io/reviews/hypar-io/elements/920#-NHwLQ4v-DUPzNhemg5r:-NHxei7P8RK1rjg5gfmz:b-5jr6ww) ([raw file](https://github.com/hypar-io/elements/blob/98e7714306e71252de398e3d1124b6ca9f766f8c/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRoutingWeightModifier.cs#L77)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

-1 is a confusing value here, since we're looking for the "min" shouldn't we have this set to MaxValue?  Or maybe better, have it be a `double?` so that we can return null if there is no modified value, and then just don't modify the value if a null is returned.  
</blockquote></details>

This value is never returned, as 1 is returned if no modifiers are applied. But you are correct, using MaxValue makes everything much simpler.



_Code quote:_
```Smalltalk
double modifierFactor = -1
```
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRoutingWeightModifier.cs` line 76 at r2](https://reviewable.io/reviews/hypar-io/elements/920#-NI0WR1EEI0m6bbjCJkS:-NI2IAIbBWg6q9R3OkqR:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/b8c972fba0e349bbea8c7dd8e657fbcf391944c2/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRoutingWeightModifier.cs#L76)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

"and returns"  add 's'
</blockquote></details>

Done.
___
*[`Elements/src/Spatial/AdaptiveGrid/EdgeFlags.cs` line 8 at r2](https://reviewable.io/reviews/hypar-io/elements/920#-NI0W8iQ3A_KZC8gm4Az:-NI2IE6X8QlAZI_RXJQT:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/b8c972fba0e349bbea8c7dd8e657fbcf391944c2/Elements/src/Spatial/AdaptiveGrid/EdgeFlags.cs#L8)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

remove "describing"
</blockquote></details>

Done.



_Code quote:_
```Smalltalk
Bit set of flags storing describing information about edge.
```
___
*[`Elements/src/Spatial/AdaptiveGrid/EdgeFlags.cs` line 12 at r2](https://reviewable.io/reviews/hypar-io/elements/920#-NI0WL7134ZKUrmU7K69:-NI2IHWz5NmKWfkbrHRN:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/b8c972fba0e349bbea8c7dd8e657fbcf391944c2/Elements/src/Spatial/AdaptiveGrid/EdgeFlags.cs#L12)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

remove extra "but"
</blockquote></details>

Done.



_Code quote:_
```Smalltalk
    /// Use & o [...]

2022-11-29 13:56 UTC, wynged requested changes
couple more comment changes before merge, but approved!

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/920#-:-NI0ZRSM4vtrMVIsjo4o:b-qljxhk)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @DmytroMuravskyi)

___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs` line 109 at r1](https://reviewable.io/reviews/hypar-io/elements/920#-NHwJNvuBqmXXZAczNgb:-NI2boE04s33x2dwLx1o:b2brpnd) ([raw file](https://github.com/hypar-io/elements/blob/98e7714306e71252de398e3d1124b6ca9f766f8c/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs#L109)):*
<details><summary><i>Previously, DmytroMuravskyi wrote…</i></summary><blockquote>

Yes that's right, however I don't think we should introduce color into data model:
-  It's hard to avoid color overlapping when to things are accidentally the same color.
- Since Edge can be affected by hint and modifier right now I wanted to distinguish hint edge and hint edge affected by modifier.
I was thinking about automatically painting edges in gradient from green to red, where yellow is factor of 1, less than that is green shifted and more than one is red shifted. What's about doing this as separate PR, maybe when we know what we want to do with edges affected by several modifiers?
</blockquote></details>

that's fine with me. let's handle this in a separate PR when we are more sure of what we want.  I see you added the Factors to the edge weights below so this is fine for now.  
___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRoutingWeightModifier.cs` line 55 at r1](https://reviewable.io/reviews/hypar-io/elements/920#-NHwKjn14kGkfFdTvjg4:-NI2dgfs341PMPImvnbh:bz46wk5) ([raw file](https://github.com/hypar-io/elements/blob/98e7714306e71252de398e3d1124b6ca9f766f8c/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRoutingWeightModifier.cs#L55)):*
<details><summary><i>Previously, DmytroMuravskyi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

missing the extra "the"


<!-- Sent from Reviewable.io -->

2022-11-29 13:57 UTC, wynged approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/920#-:-NI2fVx65fwee0T23yJE:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @DmytroMuravskyi)



<!-- Sent from Reviewable.io -->

2022-11-29 14:06 UTC, DmytroMuravskyi reviewed
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/920)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @wynged)

___
*[`Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRoutingWeightModifier.cs` line 55 at r1](https://reviewable.io/reviews/hypar-io/elements/920#-NHwKjn14kGkfFdTvjg4:-NI2hNNi4s06U7bZpOJE:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/98e7714306e71252de398e3d1124b6ca9f766f8c/Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRoutingWeightModifier.cs#L55)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

missing the extra "the"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-29 14:16 UTC, merged