Element drawing
hypar-io/Elements pull request #930
Opened 2022-12-13 00:27 UTC by katehryhorenko

DESCRIPTION:
This PR contains class that allows to create SVG / PDF drawing of an element. How it works:
1. It collects all edges from the faces visible under required angle
2. Projects collected edges to the plane (normal to plane = input angle)
3. Creates dimension lines near element boundaries. 
4. Checks if there is enough space to insert text and creates leaders if required

![image](https://user-images.githubusercontent.com/88673491/207194431-86056957-d6b9-49f3-8042-0c139819df99.png)

TESTING:
- I tested it on different models inside PanelMax Exporter together with Drywall function 
  
FUTURE WORK:
- Extend svg ViewBox to include dimension lines. Currently I'm extending to include 3 possible dimension lines on each side. But this value should be calculated
- Use SkCanvas instead of SvgDocument
- Encapsulate common logic from SvgSection and SvgElementSection to the base class 

REQUIRED:
- [ ] All changes are up to date in `CHANGELOG.md`.

2022-12-14 00:46 UTC, ikeough requested changes
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/930)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @katehryhorenko)

___
*[`Elements/src/Units.cs` line 111 at r1](https://reviewable.io/reviews/hypar-io/elements/930#-NJD0mC90e7xDC5Jv0a0:-NJD0mC90e7xDC5Jv0a1:b-ec3h6p) ([raw file](https://github.com/hypar-io/elements/blob/69d3d5ed9d489a7e953670327a838e72ec62c910/Elements/src/Units.cs#L111)):*
> ```Smalltalk
>         /// <summary>
>         /// Convert from decimal feet to feet and fractional inches
>         /// </summary>
> ```

I know these comments were taken from the original location, but can we expand them to include comments for all the parameters? It would be nice for the user to know what "precision" means for example.
___
*[`Elements/src/Units.cs` line 157 at r1](https://reviewable.io/reviews/hypar-io/elements/930#-NJD1-Wf857KTDxaNWmh:-NJD1-Wf857KTDxaNWmi:b-r0mhqh) ([raw file](https://github.com/hypar-io/elements/blob/69d3d5ed9d489a7e953670327a838e72ec62c910/Elements/src/Units.cs#L157)):*
> ```Smalltalk
>         /// <summary>
>         /// Convert from decimal inches to fractional inches
>         /// </summary>
> ```

Same note as above about expanding comments.


<!-- Sent from Reviewable.io -->

2022-12-16 00:46 UTC, ikeough commented
We would like to use the work that is done in this PR related to dimension layout to further improve the work earlier done on `Annotation` `LinearDimension` and `AlignedDimension`. Then `SvgElementSection` can become `SvgFaceElevation` as we're not really creating a .

```c#
public class Face
{
  ...
  List<LinearDimension> CreateDimensions()
  {
    // Insert code taken from SvgElementSection, replacing the normal used in SvgElementSection with the normal of the face.
  }
}

public class SvgFaceElevation
{
  public SvgFaceElevation(Face face, Vector3 up)
  {
     // Use our new method here to create all the dimensions of the face.
     var dimensions = face.CreateDimensions();
       
     // Use the up vector to to orient the face on the 'page' when generating the SVG or PDF
  }
}
```

2023-01-03 21:02 UTC, katehryhorenko reviewed
I renamed SvgElementSection with SvgFaceElevation. Maybe it should be SvgFacePlan or SvgFaceDrawing?

I started CreateDimensions implementation. But this change doesn't look easy. Currently I'm drawing a few dimensions on one line, but LinearDimension is one  line per dimension. And a lot of nuances like this. I'm suggestion to go ahead with this PR. The CreateDimensions will not change the interface of this class, so I think it shouldn't be a blocker :thinking: 

> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/930#-:-NKtQCdLAE9ISYBulDu3:b-viqdnm)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough)

___
*[`Elements/src/Units.cs` line 111 at r1](https://reviewable.io/reviews/hypar-io/elements/930#-NJD0mC90e7xDC5Jv0a0:-NKtQ8Ww7wlsRRdSlH2l:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/69d3d5ed9d489a7e953670327a838e72ec62c910/Elements/src/Units.cs#L111)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

I know these comments were taken from the original location, but can we expand them to include comments for all the parameters? It would be nice for the user to know what "precision" means for example.
</blockquote></details>

Done.
___
*[`Elements/src/Units.cs` line 157 at r1](https://reviewable.io/reviews/hypar-io/elements/930#-NJD1-Wf857KTDxaNWmh:-NKtQAMG7SNwdnuGLhml:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/69d3d5ed9d489a7e953670327a838e72ec62c910/Elements/src/Units.cs#L157)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

Same note as above about expanding comments.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-10 00:10 UTC, ikeough requested changes
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/930)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @katehryhorenko)

___
*[`Elements/src/Units.cs` line 110 at r3](https://reviewable.io/reviews/hypar-io/elements/930#-NLO-S55E_4HpG7bNwrJ:-NLO-S55E_4HpG7bNwrK:b-iya109) ([raw file](https://github.com/hypar-io/elements/blob/bc83f31dab02efe94cb1e8502dc42bd6840e1a6b/Elements/src/Units.cs#L110)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// Convert from decimal feet to feet and fractional inches
> ```

"...and fractional inches." (note period)
___
*[`Elements/src/Units.cs` line 113 at r3](https://reviewable.io/reviews/hypar-io/elements/930#-NLNlRZlB2yL6h3SIIaW:-NLNlRZlB2yL6h3SIIaX:b-qs6wis) ([raw file](https://github.com/hypar-io/elements/blob/bc83f31dab02efe94cb1e8502dc42bd6840e1a6b/Elements/src/Units.cs#L113)):*
> ```Smalltalk
>         /// </summary>
>         /// <param name="decimalFeet">The value to convert to a fractional inches representation.</param>
>         /// <param name="roundDigits"></param>
> ```

"The number of fractional digits in the return value." (stolen from the c# docs, as this just sets the value for Math.Round)
___
*[`Elements/src/Units.cs` line 163 at r3](https://reviewable.io/reviews/hypar-io/elements/930#-NLNl_tJB6kVgl4jGmCN:-NLNl_tJB6kVgl4jGmCO:b-qs6wis) ([raw file](https://github.com/hypar-io/elements/blob/bc83f31dab02efe94cb1e8502dc42bd6840e1a6b/Elements/src/Units.cs#L163)):*
> ```Smalltalk
>         /// </summary>
>         /// <param name="decimalInches">The value to convert to a fractional inches representation.</param>
>         /// <param name="roundDigits"></param>
> ```

"The number of fractional digits in the return value." (stolen from the c# docs, as this just sets the value for Math.Round)
___
*[`Elements.Serialization.SVG/src/SvgFaceElevation.cs` line 52 at r3](https://reviewable.io/reviews/hypar-io/elements/930#-NLNmXb4D0uf67nEf4vI:-NLNmXb4D0uf67nEf4vJ:b-lwizoy) ([raw file](https://github.com/hypar-io/elements/blob/bc83f31dab02efe94cb1e8502dc42bd6840e1a6b/Elements.Serialization.SVG/src/SvgFaceElevation.cs#L52)):*
> ```Smalltalk
>         /// Initializes a new instance of SvgElementSection class.
>         /// </summary>
>         /// <param name="face">The element to include to the drawing.</param>
> ```

Recommend: "The face to draw."
___
*[`Elements.Serialization.SVG/src/SvgFaceElevation.cs` line 413 at r3](https://reviewable.io/reviews/hypar-io/elements/930#-NLNmGs_Em-pXbwzVsDl:-NLNmGs_Em-pXbwzVsDm:b-9lb8gv) ([raw file](https://github.com/hypar-io/elements/blob/bc83f31dab02efe94cb1e8502dc42bd6840e1a6b/Elements.Serialization.SVG/src/SvgFaceElevation.cs#L413)):*
> ```Smalltalk
>             foreach (var line in lines)
>             {
>                 var dimensionLine = FindDimenssionLine(line, false);
> ```

Suggested rename of the method to `FindDimensionLine`
___
*[`Elements.Serialization.SVG/src/SvgFaceElevation.cs` line 552 at r3](https://reviewable.io/reviews/hypar-io/elements/930#-NLNyRH21CRLDDG5dxK-:-NLNyRH21CRLDDG5dxK0:b-mmzejm) ([raw file](https://github.com/hypar-io/elements/blob/bc83f31dab02efe94cb1e8502dc42bd6840e1a6b/Elements.Serialization.SVG/src/SvgFaceElevation.cs#L552)):*
> ```Smalltalk
>         }
> 
>         private DimensionLine FindDimenssionLine(Line line, bool isOpening)
> ```

"FindDimensionLine"


<!-- Sent from Reviewable.io -->

2023-01-10 00:20 UTC, ikeough requested changes
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/930)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @katehryhorenko)

___
*[`Elements.Serialization.SVG/src/SvgFaceElevation.cs` line 50 at r3](https://reviewable.io/reviews/hypar-io/elements/930#-NLO1sc5C0P0pmkCvnIH:-NLO1sc68gteT1jh5C2g:b-lzclsx) ([raw file](https://github.com/hypar-io/elements/blob/bc83f31dab02efe94cb1e8502dc42bd6840e1a6b/Elements.Serialization.SVG/src/SvgFaceElevation.cs#L50)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// Initializes a new instance of SvgElementSection class.
> ```

"Initializes a new instance of SvgFaceElevation class."


<!-- Sent from Reviewable.io -->

2023-01-10 14:16 UTC, katehryhorenko reviewed
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/930)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ikeough)

___
*[`Elements/src/Units.cs` line 113 at r3](https://reviewable.io/reviews/hypar-io/elements/930#-NLNlRZlB2yL6h3SIIaW:-NLQwbir02gayMeqdmdg:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/bc83f31dab02efe94cb1e8502dc42bd6840e1a6b/Elements/src/Units.cs#L113)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

"The number of fractional digits in the return value." (stolen from the c# docs, as this just sets the value for Math.Round)
</blockquote></details>

Done.
___
*[`Elements/src/Units.cs` line 163 at r3](https://reviewable.io/reviews/hypar-io/elements/930#-NLNl_tJB6kVgl4jGmCN:-NLQwcFsDK3s0x6Bl4v4:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/bc83f31dab02efe94cb1e8502dc42bd6840e1a6b/Elements/src/Units.cs#L163)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

"The number of fractional digits in the return value." (stolen from the c# docs, as this just sets the value for Math.Round)
</blockquote></details>

Done.
___
*[`Elements.Serialization.SVG/src/SvgFaceElevation.cs` line 50 at r3](https://reviewable.io/reviews/hypar-io/elements/930#-NLO1sc5C0P0pmkCvnIH:-NLQwdCyADxDTzCR2xvu:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/bc83f31dab02efe94cb1e8502dc42bd6840e1a6b/Elements.Serialization.SVG/src/SvgFaceElevation.cs#L50)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

"Initializes a new instance of SvgFaceElevation class."
</blockquote></details>

Done.
___
*[`Elements.Serialization.SVG/src/SvgFaceElevation.cs` line 52 at r3](https://reviewable.io/reviews/hypar-io/elements/930#-NLNmXb4D0uf67nEf4vI:-NLR1OKQBkwINv56cI6F:b-896fix) ([raw file](https://github.com/hypar-io/elements/blob/bc83f31dab02efe94cb1e8502dc42bd6840e1a6b/Elements.Serialization.SVG/src/SvgFaceElevation.cs#L52)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

Recommend: "The face to draw."
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-23 19:38 UTC, ikeough approved these changes
> *[Reviewable](https://reviewable.io/reviews/hypar-io/elements/930)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @katehryhorenko)

___
*[`CHANGELOG.md` line 21 at r4](https://reviewable.io/reviews/hypar-io/elements/930#-NMV7nb17g2rr9CXCJwp:-NMV7nb17g2rr9CXCJwq:buy0c9f) ([raw file](https://github.com/hypar-io/elements/blob/1dc405d68ef7d3e4de21a58b258e7be63eca5a09/CHANGELOG.md#L21)):*
> ```Markdown
> - `RoutingHintLine.IsNearby`
> - `RoutingHintLine.Affects`
> - `SvgElementSection`
> ```

Replace with`SvgFaceElevation`.


<!-- Sent from Reviewable.io -->

2023-01-24 13:44 UTC, merged